#!/bin/sh
TMPROOT=$(mktemp -d)
OPENWRT=${PWD}
BINDIR=${OPENWRT}/bin/targets/sunxi/cortexa53
BOOTDIR=${OPENWRT}/build_dir/target-aarch64_cortex-a53_musl/root-sunxi/boot
ROOT=openwrt-sunxi-cortexa53-device-sun50i-h5-nanopi-neo-plus2-rootfs.tar.gz
ATLASROOT=openwrt-sunxi-cortexa53-atlas-rootfs.tar
FIRMWARE_APPS_VERSION_FILE=${TMPROOT}/home/atlas/state/FIRMWARE_APPS_VERSION

for NEEDED in include package tools scripts target toolchain; do
	if [ ! -d "${OPENWRT}/${NEEDED}" ]; then
		echo 'Please execute from an OpenWRT v4 directory'
		rm -rf ${TMPROOT}
		exit 1
	fi
done

if ( [ ! -d "${OPENWRT}/build_dir" ] ||
     [ ! -d "${OPENWRT}/staging_dir" ] ||
     [ ! -d "${BINDIR}" ] ||
     [ ! -f "${BINDIR}/${ROOT}" ] ||
     [ ! -d "${BOOTDIR}" ] ); then
	echo 'Please execute from a built OpenWRT v4 directory'
	rm -rf ${TMPROOT}
	exit 1
fi

(cd ${TMPROOT} && tar xfz ${BINDIR}/${ROOT})

mkdir $TMPROOT/boot
cd ${TMPROOT}/boot
cp ${BOOTDIR}/boot.scr .
cp ${BOOTDIR}/dtb .
cp ${BOOTDIR}/sun50i-h5-nanopi-neo-plus2-boot-emmc-p2.scr .
cp ${BOOTDIR}/sun50i-h5-nanopi-neo-plus2-boot-emmc-p3.scr .
cp ${BOOTDIR}/sun50i-h5-nanopi-neo-plus2-boot-usd-p1.scr .
cp ${BOOTDIR}/sun50i-h5-nanopi-neo-plus2-u-boot-with-spl.bin .
cp ${BOOTDIR}/uImage .

# Now create the image file
(cd ${TMPROOT} && tar cf ${BINDIR}/${ATLASROOT} .)

FIRMWARE_APPS_VERSION=`cat ${FIRMWARE_APPS_VERSION_FILE}`
echo  "build version ${FIRMWARE_APPS_VERSION}"
ROOTFS_VERSION="${FIRMWARE_APPS_VERSION}"
ROOTFS_FILE="rootfs-${ROOTFS_VERSION}.img.bz2"

cd $BINDIR  

rm -f "${ROOTFS_FILE}"
bzip2 -c -1 "${ATLASROOT}" > "${ROOTFS_FILE}"
rm -rf ${TMPROOT}
